image: docker:latest

services:
  - docker:dind

variables:
  STAGING_REGISTRY: "registry.gitlab.com"

stages:
  - build
  - test

build:
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u larsnow -p $CI_BUILD_TOKEN ${STAGING_REGISTRY}
    # - docker info
    - apk update
    - apk upgrade
    - apk add python python-dev py-pip build-base
    - pip install docker-compose

  stage: build
  script:
    - docker-compose -f docker-compose.yml build
    - docker-compose -f docker-compose.yml up -d

  only:
    - master

test:
  stage: test
  script:
    - echo "Test OK"
