sudo: true
language: php
php:
  - '5.6'
env:
  - SYMFONY_VERSION="2.8.*" DB=mysql
  - SYMFONY_VERSION="dev-master" DB=mysql

install:
   - composer require symfony/framework-bundle:${SYMFONY_VERSION}
