sudo: required

env:
  DOCKER_COMPOSE_VERSION: 1.16.0

services:
  - docker

before_install:
  - docker info
  # - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - docker-compose -v
  - docker -v
  - mkdir symfony

script:
  - docker-compose -f docker-compose.yml build
  - docker-compose -f docker-compose.yml up -d
  - docker-compose -f docker-compose.yml ps
